[package]
name = "nickray"
version = "0.0.1"
authors = ["Nicolas Stalder <n@stalder.io>"]
license = "MIT OR Apache-2.0"
description = "docs.rs as a publishing platform?"
documentation = "https://docs.rs/nickray"
edition = "2018"
